clear all; close all; clc;

Image = imread('cameraman.tif');
Image = mat2gray(Image);
result1 = Image;
result2 = Image;
mask = fspecial('average', [5 5]);

mask_hx = (1/5)*ones(1,5);
mask_hy = (1/5)*ones(5,1);

tic;
for i=3:1:size(Image,1)-3
    for j=3:1:size(Image,2)-3
        result1(i,j) =  Image(i-2,j-2) *   mask(1,1)+...
                        Image(i-2,j-1) *    mask(1,2)+...
                        Image(i-2,j) *      mask(1,3 )+...
                        Image(i-2,j+1) * 	mask(1,4 )+...
                        Image(i-2,j+2) * 	mask(1,5 )+...
                        Image(i-1,j-2) * 	mask(2,1)+...
                        Image(i-1,j-1) * 	mask(2,2)+...
                        Image(i-1,j) * 		mask(2,3 )+...
                        Image(i-1,j+1) * 	mask(2,4 )+...
                        Image(i-1,j+2) * 	mask(2,5 )+...
                        Image(i,j-2) * 		mask(3,1)+...
                        Image(i,j-1) * 		mask(3,2)+...
                        Image(i,j) * 		mask(3,3 )+...
                        Image(i,j+1) * 		mask(3,4 )+...
                        Image(i,j+2) * 		mask(3,5 )+...
                        Image(i+1,j-2) * 	mask(4,1)+...
                        Image(i+1,j-1) * 	mask(4,2)+...
                        Image(i+1,j) * 		mask(4,3 )+...
                        Image(i+1,j+1) * 	mask(4,4 )+...
                        Image(i+1,j+2) * 	mask(4,5 )+...
                        Image(i+2,j-2) * 	mask(5,1)+...
                        Image(i+2,j-1) * 	mask(5,2)+...
                        Image(i+2,j) * 		mask(5,3 )+...
                        Image(i+2,j+1) * 	mask(5,4 )+...
                        Image(i+2,j+2) * 	mask(5,5 );
    end
end
t1 = toc
tic
for j=3:1:size(Image,2)-3
    for i=3:1:size(Image,1)-3
        result2(i ,j) = ...
                        Image(i-2,j)*mask_hy(1) +...
                        Image(i-1,j)*mask_hy(2) +...
                        Image(i-0,j)*mask_hy(3) +...
                        Image(i+1,j)*mask_hy(4) +...
                        Image(i+2,j)*mask_hy(5);
    end
end
for i=3:1:size(Image,1)-3
    for j=3:1:size(Image,2)-3
        result2(i ,j) = ...
            result2(i,j-2)*mask_hx(1) +...
            result2(i,j-1)*mask_hx(2) +...
            result2(i,j+0)*mask_hx(3) +...
            result2(i,j+1)*mask_hx(4) +...
            result2(i,j+2)*mask_hx(5);
    end
end 
t2 = toc
subplot(1,2,1)
imshow(result1);
title('t1: ');
subplot(1,2,2)
imshow(result2);
title('t2: ');